### ISSUE TITLE
Black LCD screens with the latest salty-dev from 09.04.2022

### ISSUE THREAD

**Issue by BaloneyGeek** [RobSimulation/robsim-salty-777#57]
Hi,

I just updated both my salty-747 with the latest dev package from today (09.04.2022 17:33 CEST) and the latest development package of this repo. Unfortunately all screens are now black. The controls and switches seem to be fine.

Thanks,
Boud

**Comment by masterrob94** [comment]
Please use flightsim.to version. Current dev version isn't merged for testing right now
