### ISSUE TITLE
767 Flaperon 

### ISSUE THREAD

**Issue by jasonrones** [RobSimulation/robsim-salty-777#69]
Flaperons on the 767-400 seem to be stuck in place.
![Screenshot 2022-05-03 161308](https://user-images.githubusercontent.com/62684245/166558363-fd854fc6-29d6-427b-88d6-415c24ff2164.png)

**Comment by masterrob94** [comment]
Known issue with currently missing WASM module for 767

**Comment by masterrob94** [comment]
Fixed with 2.16.1 update
